name: Deployment Pipeline

on:
  push:
    branches: [main]

jobs:
  hello_word:
    runs-on: ubuntu-18.04
    steps:
      - name: Deployment Pipeline
        run: |
          echo "Deployment Pipeline is running successfully"

