name: Deployment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [develop]
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: npm run check:eslint -f

  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install -no-audit --no-fund --no-optional -f
