name: Deployment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [develop]
    types: [opened, synchronize]

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install -no-audit --no-fund --no-optional -f

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: run test
    - run: npm run check:eslint -f

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Build
    - run: npm run build -f
